apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-nginx
  namespace: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
        role: client
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
        - image: launcher.gcr.io/google/nginx1
          name: nginx
          volumeMounts:
            - name: site-conf
              mountPath: /etc/nginx/conf.d
            - name: site-top-html
              mountPath: /usr/share/nginx/html
            - name: htpasswd
              mountPath: /etc/nginx/htpasswd
        - image: elasticsearch:local
          name: elasticsearch-client
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_MASTER
            value: "false"
          - name: NODE_DATA
            value: "false"
          - name: "ES_JAVA_OPTS"
            value: "-Xms256m -Xmx256m"
          ports:
          - containerPort: 9200
            name: http
            protocol: TCP
          - containerPort: 9300
            name: transport
            protocol: TCP
          volumeMounts:
          - name: storage
            mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: site-conf
          configMap:
            name: site-conf
        - name: site-top-html
          configMap:
            name: site-top-html
        - name: "storage"
          emptyDir:
            medium: ""
        - name: htpasswd
          secret:
            secretName: htpasswd
