apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-kibana
  namespace: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
        role: kibana
    spec:
      containers:
        - image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
          name: elasticsearch
          env:
          - name: discovery.type
            value: "single-node"
          ports:
          - containerPort: 9200
            name: http
            protocol: TCP
          - containerPort: 9300
            name: transport
            protocol: TCP
          volumeMounts:
          - name: storage
            mountPath: /usr/share/elasticsearch/data
        - image: docker.elastic.co/kibana/kibana-oss:6.2.4
          name: kibana
          env:
          - name: ELASTICSEARCH_URL
            value: "http://localhost:9200"
          ports:
          - containerPort: 5601
            name: http
            protocol: TCP
      volumes:
        - name: "storage"
          emptyDir:
            medium: ""
