apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elasticsearch
  labels:
    app: elasticsearch
    role: kibana
spec:
  type: LoadBalancer
  selector:
    app: elasticsearch
    role: kibana
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5601
    name: http
  - protocol: TCP
    port: 9200
    targetPort: 9200
    name: transport
